version: '3'

services:
  eventhubgenerator:
    image: eventhubgenerator:dev
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_eventhubgenerator$
    volumes:
      - C:\Users\lalofran\source\repos\EventHubGenerator\EventHubGenerator:/app
      - C:\Users\lalofran\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_eventhubgenerator$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_eventhubgenerator$ bin/Debug/netcoreapp2.0/EventHubGenerator.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
